/*
Catch study 15주차
프로그래머스_압축
https://programmers.co.kr/learn/courses/30/lessons/17684
*/
/*-----------------
풀이
해쉬
-----------------*/
#include <string>
#include <vector>
#include <unordered_map>
#include <iostream>
using namespace std;
std::unordered_map<std::string, int> mp;
void init() {
	for (int i = 0; i < 26; i++) mp[std::string(1, i+'A')] = i + 1;
}

vector<int> solution(string msg) {
	vector<int> answer;
	init();
	int i = 1,idx=27;
	string now = std::string(1, msg[0]), pre = std::string(1, msg[0]);
	
	while (i < msg.size()) {
		now += msg[i];
		if (!mp[now]) {
			mp[now] = idx;
			idx++;
			answer.push_back(mp[pre]);
			pre = now = std::string(1, msg[i]);
			now = pre;
		}
		i++;
		pre = now;
	}
	answer.push_back(mp[pre]);
	return answer;
}

int main() {
	std::string msg = "KAKAO";
	msg = "TOBEORNOTTOBEORTOBEORNOT";
	//msg = "ABABABABABABABAB";
	//msg = "THATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITIS";
	
	std::vector<int> answer = solution(msg);
	for (int i = 0; i < answer.size(); i++)
		std::cout << answer[i] << " ";
	std::cout << '\n';
	
	return 0;
}